bii_webapp/apps/accounts/urls.py
from django.conf.urls import *
from django.views.generic.base import TemplateView
from registration.forms import RegistrationFormUniqueEmail
from registration.views import activate
from views import profile

urlpatterns = patterns('',
                         url('register/$', 'registration.views.register',
                         {'form_class': RegistrationFormUniqueEmail,
                         'backend': 'registration.backends.default.DefaultBackend'},
                         name='registration_register'),
                       url(r'^activate/complete/$',
                           TemplateView.as_view(template_name='registration/activation_complete.html'),
                           name='registration_activation_complete'),
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           activate,
                           {'backend': 'registration.backends.default.DefaultBackend'},
                           name='registration_activate'),
                       url(r'^register/complete/$',
                           TemplateView.as_view(template_name='registration/registration_complete.html'),
                           name='registration_complete'),
                       url(r'^register/closed/$',
                           TemplateView.as_view(template_name='registration/registration_closed.html'),
                           name='registration_disallowed'),
                       (r'', include('registration.auth_urls')),
                       
                       url(r'^email/change/$', 'email_change.views.email_change_view', name='email_change'),
                       url(r'^email/verification/sent/$',
                           TemplateView.as_view(template_name='email_change/email_verification_sent.html'),
                           name='email_verification_sent'),
                        # Note taken from django-registration
                        # Verification keys get matched by \w+ instead of the more specific
                        # [a-fA-F0-9]{40} because a bad verification key should still get to the view;
                        # that way it can return a sensible "invalid key" message instead of a
                        # confusing 404.
                        url(r'^email/verify/(?P<verification_key>\w+)/$', 'email_change.views.email_verify_view', name='email_verify'),
                        url(r'^email/change/complete/$',
                            TemplateView.as_view(template_name='email_change/email_change_complete.html'),
                            name='email_change_complete'),
                       
                       url(r'^password/change/$',
                            TemplateView.as_view(template_name='registration/password_change_form.html'),
                            name='password_change'),
                       
                       url(r'^profile/$',profile,
                          name='accounts.profile'),
                       )

bii_webapp/urls.py
from django.conf.urls import patterns, include, url
# from accounts.forms import RegistrationFormWithUniqueEmailAndName
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^accounts/', include('bii_webapp.apps.accounts.urls')),
    url(r'^browse/', include('bii_webapp.apps.browse.urls')),
    url(r'^create/', include('bii_webapp.apps.create.urls')),
    url(r'^$',include('bii_webapp.apps.base.urls')),
    url(r'^upload/', include('bii_webapp.apps.upload.urls')),
    # url(r'^files/', include('bii_webapp.apps.files.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bii_webapp/static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    )


bii_webapp/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# class B(models.Model):
#     b1=models.CharField(max_length=200)
#  
class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    website = models.URLField("Website", blank=True)
    company = models.CharField(max_length=50, blank=True)

bii_webapp/apps/accounts/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from models import UserProfile

class UserForm(forms.ModelForm):
    class Meta:
                model = User
                exclude=('last_login','date_joined','is_active','is_superuser','is_staff')
                
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={'readonly':'readonly','value':'00000000000000000'}))
        
    first_name = forms.RegexField(regex=r'^[\w.@+-]+$',
                                max_length=30,
                                required=False,
                                widget=forms.TextInput(),
                                label=_("First Name"),
                                error_messages={'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")})
    last_name = forms.RegexField(regex=r'^[\w.@+-]+$',
                                max_length=30,
                                required=False,
                                widget=forms.TextInput(),
                                label=_("Last Name"),
                                error_messages={'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")})
    
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))


class ProfileForm(forms.ModelForm):
    class Meta:
                model = UserProfile
                exclude=('user')
                
    website=forms.URLField(label=_("Website"),
                           widget=forms.TextInput(),
                           required=False,
                           error_messages={'invalid': _("This value must be in the form of a website link")})
    
    company = forms.RegexField(regex=r'^[\w.@+-]+$',
                                required=False,
                                widget=forms.TextInput(),
                                label=_("Company"),
                                error_messages={'invalid': _("This value may contain only letters, numbers and @/./+/-/_ characters.")})
    
    
        

bii_webapp/apps/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect,render

from forms import ProfileForm,UserForm
from models import UserProfile


@login_required
def profile(request):
    user = request.user
    profile,created=UserProfile.objects.get_or_create(user=user)
    
    if request.method=='POST':
        profileform = ProfileForm(request.POST,instance=profile)
        userform = UserForm(request.POST,instance=user)
        if profileform.is_valid() and userform.is_valid():
            profileform.save()
            userform.save()
            return redirect('bii_webapp.apps.browse.views.browse')
    else:
        profileform=ProfileForm(instance=profile)
        userform=UserForm(instance=user)
        
        return render(request,'profiles/profile.html',{'profileform':profileform,'userform':userform})
    
    return render(request,'profiles/profile.html',{'profileform':profileform,'userform':userform})
    

bii_webapp/apps/accounts/templates/email_change/email_base.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block extracss %}
<link href="{% static 'accounts/css/forms.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
{% endblock %}

bii_webapp/apps/accounts/templates/email_change/email_change_complete.html
{% extends "email_change/email_base.html" %}
{% load i18n %}

{% block title %}{% trans "Email change complete" %}{% endblock %}

{% block breadcrumbs-box %}
    {{ block.super }} &rsaquo; {% trans "Notice" %}
{% endblock %}

{% block coltype %}login{% endblock %}

{% block content_title %}
    <h1>{% trans "Email change complete" %}</h1>
{% endblock %}

{% block content %}
    <div id="content-main">
        <p>{% trans "Your email address has been changed successfully." %}</p>
        <p>{% trans "Your new email address is:" %}</p>
        <blockquote>{{ user.email }}</blockquote>
        <p>&laquo; <a href="{% url 'accounts.profile' %}">{% trans "Back to your profile" %}</a></p>
    </div>
{% endblock %}



bii_webapp/apps/accounts/templates/email_change/email_change_form.html
{% extends "email_change/email_base.html" %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans "Change email address" %}{% endblock %}

{% block breadcrumbs-box %}
{{ block.super }} &rsaquo; {% trans 'Change email address' %}
{% endblock %}

{% block coltype %}login{% endblock %}

{% block content_title %}
<h1>{% trans "Change email address" %}</h1>
{% endblock %}

{% block content %}
<div id="content-main">
	<p>
		{% trans "Your current email address is:" %}
	</p>
	<blockquote>
		{{ user.email }}
	</blockquote>
	<p>
		{% trans "To associate a new email address with your account, please enter the new address in the box below." %}
	</p>
	<form method="post">
		{% csrf_token %} <label for="id_email">Email address:</label>

		{% if form.email.errors %}
		<p class="errors">
			{{ form.email.errors.as_text }}
		</p>
		{% endif %}
		{{ form.email|add_class:"field" }}
		<p>
			<label>&nbsp;</label>
			<input class="btn btn-info" type="submit" value="{% trans "Change email address" %}" />
		</p>
	</form>
	<p>
		&laquo; <a href="{% url 'accounts.profile' %}">{% trans "Back to your profile" %}</a>
	</p>
</div>
{% endblock %}


bii_webapp/apps/accounts/templates/email_change/email_verification_sent.html
{% extends "email_change/email_base.html" %}
{% load i18n %}

{% block title %}{% trans "Verification email sent" %}{% endblock %}

{% block breadcrumbs-box %}
    {{ block.super }} &rsaquo; {% trans "Notice" %}
{% endblock %}

{% block coltype %}login{% endblock %}

{% block content_title %}
    <h1>{% trans "Verification email sent" %}</h1>
{% endblock %}

{% block content %}
    <div id="content-main">
        <p>{% trans "An email containing a verification link has been sent to your new email address." %}</p>
        <p>{% trans "Follow the instructions in this email in order to successfully change your current email address." %}</p>
        <p>&laquo; <a href="{% url 'accounts.profile'%}">{% trans "Back to your profile" %}</a></p>
    </div>
{% endblock %}


bii_webapp/apps/accounts/templates/email_change/email_verify.html
{% extends "email_change/email_base.html" %}
{% load i18n %}

{% block title %}{% trans "Email confirmation" %}{% endblock %}

{% block breadcrumbs-box %}
    {{ block.super }} &rsaquo; {% trans "Notice" %}
{% endblock %}

{% block coltype %}login{% endblock %}

{% block content_title %}
    <h1>{% trans "Email confirmation failed" %}</h1>
{% endblock %}

{% block content %}
    <div id="content-main">
        <p>{% trans "This confirmation code has either expired or is invalid." %}</p>
        <p>{% trans "The requested email address change has failed." %}</p>
        <p>{% trans "Please, try to change it again in your account settings." %}</p>
        <p>&laquo; <a href="{% url profiles_profile_detail user.username %}">{% trans "Back to your profile" %}</a></p>
    </div>
{% endblock %}
